import React from "react";
import legalCSS from "../shared/styles/legal.module.css"
class TermsAndConditions extends React.Component{
    render(){
        return <>
            <div className={legalCSS.tnc_wrapper}>
                <div className={legalCSS.tnc_container}>
                    <div className={legalCSS.super_title}>Terms &amp; Conditions - Together Innovation Labs Pvt. Ltd.</div>
                    <div className={legalCSS.content_text}>These terms and conditions (“Terms &amp; Conditions”) govern your access to and use of the platform as made available through the website https://crypso.club/ and mobile application under the brand name ‘Crypso’ (collectively the “Platform”) managed and operated by ‘Together Innovation Labs Private Limited’, a company incorporated under the Companies Act, 2013 and having its registered office at L-148, 5th Main Road, Sector 6, HSR Layout, Bangalore , Bangalore, Karnataka, India, 560102  (hereinafter referred as “Us” / “We”/ “Crypso”) for general browsing or availing any services available on the Platform.</div>
                    <div className={legalCSS.content_text}>As a user (“User”/ “You” which shall mean and include any natural person who has registered, agreed to use or has accessed or is visiting the Platform), You understand that Crypso through the Platform facilitates the interaction between its Users and sharing information, inputs and feedback on forums created by Users on the Platform.</div>
                    <div className={legalCSS.content_text}>Please read these Terms &amp; Conditions carefully before accessing or using the Platform or any part thereof. By accessing or using any part of the Platform, You agree to be bound by these Terms &amp; Conditions. If You do not agree to all the Terms &amp; Conditions, then YOU MAY NOT ACCESS THE PLATFORM OR USE ANY SERVICES PROVIDED BY CRYPSO THROUGH THE PLATFORM.</div>
                    <div className={legalCSS.content_text}>“SPECIFIED DISCLAIMER: CRYPTO PRODUCTS ARE UNREGULATED AND CAN BE HIGHLY RISKY. THERE MAY BE NO REGULATORY RECOURSE FOR ANY LOSS FROM SUCH TRANSACTIONS.”</div>
                    <div className={legalCSS.content_text}>These Terms &amp; Conditions form a legal and binding agreement between You and Crypso and is made pursuant to the terms of the Information Technology Act, 2000. As long as You comply with these Terms &amp; Conditions, We grant You a personal, non-exclusive, non-transferable, non-sublicensable, revocable, limited privilege to access and use the Platform as per these Terms &amp; Conditions. By accepting these Terms &amp; Conditions, You also accept and agree to be bound by policies of Crypso including but not limited to Privacy Policy and AML Policy as amended from time to time which form a part of these Terms &amp; Conditions by reference.</div>
                    <div className={legalCSS.content_text}>
                        <ol>
                            <li>
                                General<br/>You represent and warrant that You:
                                <ol>
                                    <li>are an Indian resident.</li>
                                    <li>are at least 18 (eighteen) years old.</li>
                                    <li>are competent to form a binding contract under the Indian Contract Act, 1872.</li>
                                    <li>have not previously been suspended or your use of the Platform or any part thereof has not been restricted due to any breach or perceived breach by Crypso.</li>
                                    <li>The Platform including all materials on it, or provided to You, through it are protected by copyright, trademark and other intellectual property rights and laws throughout the world and are owned by, or are licensed to Crypso. You are permitted to display the materials on this Platform on a computer screen and/or mobile screen and, save for restricted access documents, to download and print a hard copy for your personal use, provided You do not alter or remove any of the content which may include text, graphics, images, logos, button icons, software code, design, and the collection, arrangement and assembly of content provided by Crypso (“Content”) without our express permission to do so and that You do not change or delete any copyright, trademark or other proprietary notices. Content also includes any Content created by You or through your Account and Content uploaded or posted by You on the Platform (“User Content”).</li>
                                    <li>All Content on the Platform is provided “as is” with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of the information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing contained in these Terms &amp; Conditions shall to any extent substitute for the independent investigations and the sound technical and business judgment of the User. In no event shall Crypso be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to the services, data, opinions, views or information available on the Platform.</li>
                                    <li>Crypso reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms &amp; Conditions, at any time without any prior written notice to the User. It is the User’s responsibility to review these Terms &amp; Conditions periodically for any updates/ changes. User’s continued use of the Platform following the modification of these Terms &amp; Conditions will imply the acceptance by the User of the modification.</li>
                                    <li>You hereby acknowledge and agree that Crypso is not a financial institution, bank, credit union, trust, hedge fund, broker or investment or financial advisor, and is not subject to the laws, regulations, directives or requirements applicable to such persons. You acknowledge and agree that no oral or written information or advice provided by Crypso, its officers, directors, employees, or agents, nor any information obtained through the Platform or otherwise from Crypso, will or shall constitute trading, investment or financial advice regarding the trading of cryptocurrencies, including the suitability and appropriateness of, and investment strategies for cryptocurrencies. You are solely and exclusively responsible for all trading and investment decisions made by you while using the Platform.</li>
                                    <li>User agrees and consents to be contacted by Crypso through phone calls, SMS notifications, email or any other means of communication, in respect to the services or the Platform provided by Crypso even if contact number(s) provided to Crypso are on Do Not Call Registry.</li>
                                    <li>You agree that Crypso may disclose your personal and account information if Crypso believes that it is reasonably necessary to comply with a law, regulation, legal process, or governmental request. For more details, please refer to Our Privacy Policy.</li>
                                    <li>The Platform is an online website and mobile application that facilitates sharing of data and information relating to cryptographically secured digital representation of value or contractual rights that uses distributed ledger technology and can be transferred, stored or traded electronically (“Crypto Assets”) and facilitates User engagement on various topics related to Crypto Assets (collectively, the “Services”).</li>
                                    <li>The Platform may facilitate the provisions of other services by third parties. In particular, the option to trade in Crypto Asserts is provided by Mindful Innovation Labs Private Limited (“Trading Partner”) through the website at [---] and mobile application [---] (“Trading Platform”) and subject to the terms and conditions, processes and decisions of the Trading Partner. Crypso shall not be at any time liable or responsible for action actions of the Trading Partner or any of Your transactions or other activities with the Trading Platform.</li>
                                </ol>
                            </li>
                            <li>
                                Your Account
                                <ol>
                                    <li>You may not be able avail services offered through the Platform, unless You have created an account on the Platform. To create an account (“Account”) on the Platform, You will be required to follow the registration procedure prescribed by Crypso and will be required to furnish certain information and details, including your name, email id, contact number, date of birth, address and any other information deemed necessary by Crypso.</li>
                                    <li>In the event there is mismatch in the details provided by the User or incorrect details have been provided, Crypso may at its sole discretion reject your registration or block Your Account at any time.</li>
                                    <li>You agree to provide Us with the information We request for compliance with applicable laws. You authorize Us to make the inquiries, whether directly or through third parties, that We consider appropriate, in our sole discretion, to verify your identity or protect You and/or Us against fraud or other crimes, and to take action We reasonably deem necessary based on the results of such inquiries or otherwise.</li>
                                    <li>You understand and agree that You are responsible for maintaining the confidentiality and security of your Account, password, activities that occur in or through your Account. You agree to accept responsibility for restricting and preventing unauthorized access to your Account. You agree to accept responsibility for all activities that occur under your Account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform Us immediately if You have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner or any other security breach. Crypso will not be liable for any loss or damage arising from your failure to comply with the above requirement.</li>
                                    <li>You accept and agree that your Account is for your personal use only and shall not be transferred to any other third party. You will be responsible for the activities associated with your Account in case of such transfer.</li>
                                    <li>You represent and warrant that all the details provided by You are true, correct, accurate, complete, and up to date. In the event of any change in the information provided, You agree to update the details on the Account immediately without any delay. You further represent and warrant that at the time of making a new Account, You shall inform Crypso of any existing Account(s) on the Platform.</li>
                                    <li></li>
                                    <li></li>
                                </ol>
                            </li>
                            <li>
                                Prohibited Activities <br/>Your agree not to:
                                <ol>
                                    <li>copy, reproduce, store (in any medium or format), distribute, transmit, modify, create derivate works from all or any part of the Content or the Platform or the materials or software on it, or provided to you through it without our prior written consent (which may be given or withheld in Crypso’s absolute discretion)</li>
                                    <li>use the Platform or any of the Content on it, or provided to you through it, for:
                                        <ol>
                                            <li>any unlawful purpose or in contravention of applicable law;</li>
                                            <li>commercial exploitation without our prior written consent; and</li>
                                            <li>any purpose or in any manner that may give a false or misleading impression of Us, our staff or our services.</li>
                                        </ol>
                                    </li>
                                    <li>establish a link to the Content or the Platform from any other website, intranet or extranet site that violates the provisions of Clause 3.2.</li>
                                    <li>decompile, disassemble or reverse engineer (or attempt to do any of them) any of the Content provided on or through the Platform.</li>
                                    <li>do anything that may interfere with or disrupt the Platform.</li>
                                    <li>publicly criticize, disparage, call into disrepute, or otherwise defame or slander the Platform or Crypso and any of its officers, directors, members or employees.</li>
                                    <li>encourage or permit others to do any of the above.</li>
                                    <li>In addition to what is already provided in the Terms &amp; Conditions, You represent and warrant that You shall not post, display, upload, modify, publish, transmit, update or share any information that:
                                        <ol>
                                            <li>belongs to another person and to which the User does not have any right.</li>
                                            <li>Is defamatory, obscene, pornographic, paedophilic, invasive of another person’s privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force.</li>
                                            <li>is harmful to child.</li>
                                            <li>infringes the intellectual property rights.</li>
                                            <li>violates any law for the time being in force.</li>
                                            <li>deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact.</li>
                                            <li>impersonates another person.</li>
                                            <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</li>
                                            <li>threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li>
                                            <li>spreads false and inaccurate information.</li>
                                            <li>is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.</li>
                                            <li>disrupts the services or in any way attempts to solicit users towards the services of a competitor.</li>
                                            <li>may interfere with the proper operation of this Platform or Crypso’s systems in any manner.</li>
                                        </ol>
                                    </li>
                                    <li>In the event that You do not comply with the above restrictions or Crypso has reasons to believe that You have indulged in any of the activities specified above, Crypso retains the right to immediately suspend or terminate your Account and access to the Platform, and take legal action against You, including without limitation, initiation of proceedings for claims against You for any losses and costs (including legal costs) Crypso may suffer as a result of your actions and reporting You to law enforcement authorities without providing any notice of You about any such report and confiscating any balance remaining in your Account which has been terminated. You shall further solely be liable for any claim brought against You by any other User affected by your actions.</li>
                                </ol>
                            </li>
                            <li>
                                User Content
                                <ol>
                                    <li>You hereby grant Us the worldwide, royalty free, perpetual, irrevocable, non-exclusive, and transferable rights to use, copy, modify, adapt, prepare derivative works of, distribute, store, perform, and display User Content and any name, username, voice, or likeness provided in connection with User Content in all media formats and channels now known or later developed anywhere in the world. This license includes the right for Us to make User Content available for syndication, broadcast, distribution, or publication. You also agree that We may remove metadata associated with User Content, and You irrevocably waive any claims and assertions of moral rights or attribution with respect to User Content.</li>
                                    <li>We shall be entitled to, consistent with our Privacy Policy as adopted in accordance with applicable law, use the User Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include any User Content You provide and are not entitled to any payment or other compensation for such use. You also grant Us the right to sub-license these rights, and the right to bring an action for infringement of these rights. We reserve the right to edit or remove any material submitted to this Platform, or stored on our servers, or hosted or published upon this Platform. User Content may also be visible to other users of the Platform.</li>
                                    <li>If You are posting any form of User Content on the Platform, You must verify the truthfulness and authenticity of the particulars such User Content, including the time, place and nature. Before allowing such User Content to be posted on the Platform, We have the right and authority to verify the accuracy of such particulars related to the User Content with the respective sources provided by the User posting such User Content, if We feel that there is a need to check such accuracy. We have the right to upload Content on behalf of third parties, subsequent to collecting such information and verifying it, if we deem it necessary. Notwithstanding this, We can in no way be held liable for any false or misleading information available on the Platform.</li>
                                    <li>In case any User Content is considered to be unlawful or against the law within any jurisdiction in which our Platform can be seen, it shall be removed forthwith by Us on being intimated by the authorities of the respective jurisdiction that such User Content is deemed unlawful. We cannot be held liable or questioned for the same.</li>
                                    <li>We reserve the right to maintain, delete or destroy all communications and materials posted or uploaded on the Platform according to our internal record retention and/or destruction policies. You might be contacted via the contact details provided by You to review the information provided by You. Please make sure your contact information is updated at all times.</li>
                                    <li>For additional information regarding use of information about You, please refer to the Privacy Policy. The terms “personal information” and “sensitive personal data or information” as defined under applicable laws are provided under the Privacy Policy. The Privacy policy also contains details of the type of information collected from You, including sensitive personal data or information, the purpose, means and modes of usage of such information, and how We use and disclose such information.</li>
                                    <li>We shall not be responsible in any manner for the authenticity of the personal information or sensitive personal data or information supplied by the You.</li>
                                    <li>Any information or User Content publicly posted or privately transmitted through the Platform is the sole responsibility of the User from whom such User Content originated, and your access to all such information and User Content at your own risk, and We are not liable for any errors or omissions in that information or User Content or for any damages or loss You might suffer in connection with it. We cannot control and have no duty to take any action regarding how You may interpret and use the User Content or what actions You may take as a result of having been exposed to the User Content, and You hereby release us from all liability for you having acquired or not acquired User Content through the Platform.</li>
                                    <li>You are responsible for all User Content You contribute, in any manner, to the Platform, and You represent and warrant that such User Content shall not fall within the prohibited activities detailed under clause 3.2 above. You further represent and warrant that You have all rights, power, and authority necessary to grant the rights to Crypso in the User Content as contained within these Terms &amp; Conditions.</li>
                                </ol>
                            </li>
                            <li>
                                Monitoring of the Platform and User Accounts
                                <ol>
                                    <li>Crypso always has the right and liberty to monitor the Content of the Platform or any part thereof which shall include information provided in your Account and User Content. The monitoring of the Platform is important to determine the veracity of the information provided by You and to ensure that every User remains compliant with these Terms &amp; Conditions. Subject to the Terms &amp; Conditions mentioned herein, Crypso shall also have the liberty to remove any objectionable User Content which is in contravention of these Terms &amp; Conditions or any applicable laws in force in the jurisdiction where the Platform is available to users or share such information with any governmental authority as per procedures laid down by the law for the time being in force in such jurisdiction.</li>
                                    <li>Crypso respects the intellectual property of others and requires that Users of our Services do the same. If you believe that anything on our Services infringes a copyright or a trademark that you own or control, you may notify: <b>support@crypso.club</b></li>
                                    <li>Also, please note that if you knowingly misrepresent that any activity or material on our Service is infringing, you may be liable to Reddit for certain costs and damages.</li>
                                    <li>If we remove Your Content in response to a copyright or trademark notice, we will notify you. If you believe Your Content was wrongly removed, you can send a notification to the addressee set out in Clause 5.2 above.</li>
                                </ol>
                            </li>
                            <li>
                                Suspension of Access <br/> Crypso may stop providing one or more services through the Platform and may terminate access to or use of the Platform at any time without giving notice of termination to You. Unless Crypso informs the User otherwise, upon any termination,
                                <ol>
                                    <li>the rights and licenses granted to You under these Terms &amp; Conditions will terminate forthwith</li>
                                    <li>your Account shall be suspended</li>
                                    <li>You must stop using the Platform or any part thereof forthwith</li>
                                </ol>
                                Crypso reserves the right to suspend or cease providing the Platform and shall have no liability or responsibility to the User in any manner whatsoever, except as prescribed under applicable law.<br/>
                                <ol>
                                    <li>
                                        Third Party Materials and Services
                                        <ol>
                                            <li>The Platform may provide You links to third party services (“Third Party Services”) and may display, include or make available content, data, information, applications or materials from third parties (“Third Party Materials”). You acknowledge and agree that Crypso is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third-Party Materials or Third-Party Services. CRYPSO DOES NOT WARRANT OR ENDORSE AND DOES NOT ASSUME AND WILL NOT HAVE ANY LIABILITY OR RESPONSIBILITY TO YOU OR ANY OTHER PERSON FOR ANY THIRD-PARTY SERVICES, THIRD PARTY MATERIALS OR WEBSITES, OR FOR ANY OTHER MATERIALS, PRODUCTS, OR SERVICES OF THIRD PARTIES.</li>
                                            <li>The Services may also contain sponsored Third-Party Material or advertisements. The type, degree, and targeting of advertisements are subject to change, and you acknowledge and agree that we may place advertisements in connection with the display of any Content or information on the Services, including Your Content.</li>
                                        </ol>
                                    </li>
                                    <li>
                                        Limitation of Liability and Disclaimer of Warranties
                                        <ol>
                                            <li>Notwithstanding anything to the contrary contained herein, neither Crypso nor its affiliates, subsidiaries, officers, directors, employees or any related party shall have any liability to You or to any third party for any indirect, incidental, special or consequential damages or any loss of revenue or profits or loss of data arising under or relating to these Terms &amp; Conditions even if Crypso is advised of such damages.</li>
                                            <li>Notwithstanding the foregoing, in no event will the liability of Crypso, its affiliates, subsidiaries, officers, directors, employees or any related party arising out of or in connection the services, any performance or non-performance of the services, or any other product, service or other information provided by or on behalf of Crypso whether under contract, statute, strict liability or other theory, exceed INR. 1000/- (Indian Rupee One Thousand only).</li>
                                            <li>To the maximum extent permitted by law, You waive, release, discharge and hold harmless Crypso, its affiliated and subsidiary companies, and each of their directors, officers, employees, and agents, from any and all claims, losses, damages, liabilities, expenses and causes of action arising out of your access to or use of the Platform.</li>
                                            <li>We do not guarantee our Platform will be secure, error free or free from bugs or viruses and accept no liability for loss or damage in respect of the same.</li>
                                            <li>YOUR USE OF THE PLATFORM AND ALL INFORMATION, SERVICES AND CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE PLATFORM IS AT YOUR SOLE RISK. THE PLATFORM IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS.</li>
                                            <li>Some of our Services give you access to content that belongs to other people or organizations, e.g. articles or reports shared on the Platform. You may not use such content without that person or organization’s permission, or as otherwise allowed by law. The views expressed in other people or organizations’ content are theirs, and don’t necessarily reflect Crypso’s views. Crypso may also engage persons to provide and create content for the Platform. The views expressed by such persons in their content are theirs, and don’t necessarily reflect Crypso’s views. Crypso shall not be responsible for any actions taken by you based on any content on the Platform. Crypto Assets and products are unregulated and can be highly risky. There may be no regulatory recourse for any loss from such transactions. The Reserve Bank of India (“RBI”) and the Government of India have issued multiple circulars and communications cautioning users regarding the risks involved with respect to Cryptos. Users in India shall therefore avail of the Services and access the Platform subject to the above cautions issued by the RBI and Government of India and solely at their own risk.</li>
                                        </ol>
                                    </li>
                                    <li>
                                        Indemnity
                                        <ol>
                                            <li>You agree to indemnify, save, and hold Crypso, its affiliates, contractors, employees, officers, directors, agents and its third party associates, licensors, and partners harmless from any and all claims, demands, losses, damages, and liabilities, costs and expenses, including without limitation legal fees and expenses, arising out of or related to your use or misuse of the Platform, any violation by You of these Terms &amp; Conditions, or any breach of the representations, warranties, and covenants made by You herein or your infringement of any intellectual property or other right of any person or entity, or as a result of any threatening, libellous, obscene, harassing or offensive material posted/ transmitted by You on the Platform. Crypso reserves the right, at your expense, to assume the exclusive defence and control of any matter for which You are required to indemnify Crypso, including rights to settle, and You agree to cooperate with Crypso’s defence and settlement of these claims. THIS CLAUSE SHALL SURVIVE TERMINATION OF THESE TERMS &amp; CONDITIONS.</li>
                                        </ol>
                                    </li>
                                    <li>
                                        Governing Law and Jurisdiction
                                        <ol>
                                            <li>Your access to and use of the Platform and Terms &amp; Conditions is subject to the laws of India. In case of any disputes arising out of the access to or use of the Platform or any part thereof Courts at Bengaluru, India, will have exclusive jurisdiction.</li>
                                        </ol>
                                    </li>
                                    <li>
                                        Third Party Rights<br/>Nothing in these Terms &amp; Conditions is intended to nor shall it confer a benefit on any third party who is not a party to these Terms &amp; Conditions and such third party has no rights to enforce them.
                                        <ol>
                                            <li>Waiver<br/>No delay or decision not to enforce rights under these Terms &amp; Conditions will constitute a waiver of the right to do so and will not affect rights in relation to any subsequent breach.</li>
                                            <li>Intellectual Property Rights<br/>All the intellectual property used on the Platform except those which have been identified as the intellectual properties of a User shall remain the exclusive property of Crypso. You agree not to circumvent, disable or otherwise interfere with security related features of the Platform or features that prevent or restrict use or copying of any materials or enforce limitations on use of the Platform or the materials therein. The materials on the Platform or otherwise may not be modified, copied, reproduced, distributed, republished, downloaded, displayed, sold, compiled, posted or transmitted in any form or by any means, including but not limited to, electronic, mechanical, photocopying, recording or other means.</li>
                                            <li>Termination<br/>You may terminate these Terms &amp; Conditions by ceasing to use the Platform. Crypso reserves the right to terminate your Account or access to the Platform at its sole discretion if You are found to be in breach of these Terms and &amp; Conditions or any applicable laws. In all other cases Crypso shall provide you with prior written notice of one (1) day for termination of your Account.</li>
                                            <li>Survival<br/>Even after termination Indemnity, Intellectual Property, Governing Law and any other clauses that naturally survive, shall survive the termination of these Terms &amp; Conditions.</li>
                                            <li>Severability<br/>If any provision of these Terms &amp; Conditions is deemed invalid, unlawful, void or for any other reason unenforceable, then that provision shall be deemed severable from these Terms &amp; Conditions and shall not affect the validity and enforceability of any of the remaining provisions.</li>
                                            <li>Electronic Communication<br/>The communications between You and Crypso use electronic means, whether You use the Platform or send Us emails, or whether Crypso posts notices on the Platform or communicates with You via email. For contractual purposes, You (a) consent to receive communications from Us in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that We provide to you electronically satisfy any legal requirement that such communications would satisfy if it were be in a hardcopy writing. The foregoing does not affect your non-waivable rights.</li>
                                            <li>Force Majeure<br/>Crypso shall not be liable for any damage or loss suffered by You due delay or failure in performance of Crypso’s obligations under these Terms &amp; Conditions when such delay or failure is due to causes, circumstances or events beyond its control including delay due to floods, fires, accidents, earthquakes, riots, explosions, wars, hostilities, acts of government, custom barriers, strikes, epidemic, pandemic, complete break down of telecommunication or internet services or other causes of like character. In such an event, Crypso shall be excused from any and all performance obligations.</li>
                                            <li>Grievances<br/>Crypso believes in ensuring that all the Users of the Platform are able to access and utilize the Platform to their satisfaction. Therefore, We believe in addressing any grievances or concerns that the Users have with regard to their experience on the Platform. For any queries and support, You may reach out to our Customer Support Team at support@crypso.club.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </>
    }
}
export default TermsAndConditions